# Generated by Django 6.0.4 on 2026-04-19 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': [('can_view_price', 'Puede ver precios de productos y cotizaciones')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
