# Generated by Django 6.0.4 on 2026-04-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Peso (Kg)'),
        ),
    ]
