# Generated by Django 6.0.4 on 2026-04-19 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Paquete x6, Caja x12, Display x24', max_length=100, verbose_name='Presentación')),
                ('cantidad_por_paquete', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cant. por Paquete')),
                ('precio_paquete', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Paquete (S/.)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Presentación de Producto',
                'verbose_name_plural': 'Presentaciones de Producto',
                'ordering': ['cantidad_por_paquete'],
            },
        ),
    ]
