# Generated by Django 6.0.4 on 2026-04-19 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_presentacionproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('motivo', models.CharField(help_text='Ej: Ajuste, Merma, Donación, etc.', max_length=150, verbose_name='Motivo / Concepto')),
                ('referencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro. Referencia')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.almacen', verbose_name='Almacén')),
            ],
            options={
                'verbose_name': 'Movimiento de Almacén',
                'verbose_name_plural': 'Movimientos de Almacén',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoAlmacenDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.movimientoalmacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Movimiento',
                'verbose_name_plural': 'Detalles de Movimientos',
            },
        ),
    ]
