databases:
  - name: stalex-db
    databaseName: stalex_erp
    user: stalex_user
    plan: free

services:
  - type: web
    name: stalex-erp
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stalex-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11.0
