# Generated by Django 6.0.4 on 2026-04-19 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número de Cotización')),
                ('fecha', models.DateField(verbose_name='Fecha de Cotización')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal (S/.)')),
                ('igv', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='IGV (18%) (S/.)')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total (S/.)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=15)),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contactos.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unit. (S/.)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal (S/.)')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número de Orden de Pedido')),
                ('fecha', models.DateField(verbose_name='Fecha de Pedido')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada / En Proceso'), ('DESPACHADA', 'Despachada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contactos.cliente', verbose_name='Cliente')),
                ('cotizacion_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_pedido', to='ventas.cotizacion', verbose_name='Cotización Ref.')),
            ],
            options={
                'verbose_name': 'Orden de Pedido',
                'verbose_name_plural': 'Órdenes de Pedido',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='OrdenPedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.ordenpedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Pedido',
                'verbose_name_plural': 'Detalles de Órdenes de Pedido',
            },
        ),
    ]
