# Generated by Django 6.0.4 on 2026-04-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_cotizacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenpedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada / En Proceso'), ('DESPACHADA', 'Despachada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20),
        ),
    ]
