# Generated by Django 6.0.4 on 2026-04-19 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_presentacionproducto'),
        ('ventas', '0003_alter_ordenpedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.presentacionproducto', verbose_name='Presentación'),
        ),
        migrations.AddField(
            model_name='ordenpedidodetalle',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.presentacionproducto', verbose_name='Presentación'),
        ),
    ]
