# Generated by Django 6.0.4 on 2026-04-19 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0001_initial'),
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número de Despacho')),
                ('fecha', models.DateField(verbose_name='Fecha de Despacho')),
                ('direccion_origen', models.CharField(max_length=255, verbose_name='Dirección de Origen')),
                ('direccion_destino', models.CharField(max_length=255, verbose_name='Dirección de Destino')),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden_pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ventas.ordenpedido', verbose_name='Orden de Pedido')),
                ('transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactos.transportista', verbose_name='Transportista')),
            ],
            options={
                'verbose_name': 'Orden de Despacho',
                'verbose_name_plural': 'Órdenes de Despacho',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='OrdenDespachoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='logistica.ordendespacho')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Despacho',
                'verbose_name_plural': 'Detalles de Despacho',
            },
        ),
    ]
