# Generated by Django 6.0.4 on 2026-04-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendespacho',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], default='PROGRAMADO', max_length=20),
        ),
    ]
