# Generated by Django 6.0.4 on 2026-04-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_alter_ordendespacho_estado'),
        ('ventas', '0003_alter_ordenpedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendespacho',
            name='orden_pedido',
        ),
        migrations.AddField(
            model_name='ordendespacho',
            name='ordenes_pedido',
            field=models.ManyToManyField(blank=True, related_name='despachos', to='ventas.ordenpedido', verbose_name='Órdenes de Pedido'),
        ),
        migrations.AddField(
            model_name='ordendespacho',
            name='peso_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Peso Total (Kg)'),
        ),
    ]
